import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";
import Vendor from "../models/Vendor.js";
import Category from "../models/Category.js";
import User from "../models/User.js";
import { normalizeText } from "../utils/normalizeText.js";

dotenv.config();

const products = [
  {
    name: "BEBIDA COCA COLA NORMAL 1.5L",
    price: 2183,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-COCA-COLA-NORMAL-1.5L.jpg",
    ],
    brand: "COCA COLA",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA COCA COLA ORIGINAL 3L",
    price: 3337,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/10/Bebida-Coca-Cola-Original-3-L.webp",
    ],
    brand: "COCA COLA",
    weightKg: 3.15,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA COCA COLA ZERO 1.5L",
    price: 2203,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-COCA-COLA-ZERO-1.5L.jpg",
    ],
    brand: "COCA COLA",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA COCA COLA ZERO 3L",
    price: 3337,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/10/Bebida-Coca-Cola-Zero-3-L.webp",
    ],
    brand: "COCA COLA",
    weightKg: 3.15,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA DE COCO DEYCO 400ML",
    price: 2590,
    categoryPath: "Despensa",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-DE-COCO-DEYCO-400ML.jpg",
    ],
    brand: "DEYCO",
    weightKg: 0.42,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA FANTA 1.5L",
    price: 2171,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-FANTA-1.5L.jpg",
    ],
    brand: "FANTA",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA FANTA 3L",
    price: 3337,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/11/Bebida-Fanta-3-L.webp",
    ],
    brand: "FANTA",
    weightKg: 3.15,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SCHWEPPES GINGER ALE 1.5L",
    price: 2151,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SCHWEPPES-GINGER-ALE-1.5L.jpg",
    ],
    brand: "SCHWEPPES",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SPRITE 1.5L",
    price: 2171,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SPRITE-1.5L.jpg",
    ],
    brand: "SPRITE",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SPRITE 3L",
    price: 3337,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SPRITE-3L.jpg",
    ],
    brand: "SPRITE",
    weightKg: 3.15,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SPRITE LATA 350CC 6U",
    price: 5627,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SPRITE-LATA-350CC-6U.jpg",
    ],
    brand: "SPRITE",
    weightKg: 0.37,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SPRITE ZERO 1.5L",
    price: 2130,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SPRITE-ZERO-1.5L.jpg",
    ],
    brand: "SPRITE",
    weightKg: 1.58,
    length: 9,
    width: 9,
    height: 30,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA SPRITE ZERO 3L",
    price: 3275,
    categoryPath: "Licores, Bebidas y Aguas > Bebidas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-SPRITE-ZERO-3L.jpg",
    ],
    brand: "SPRITE",
    weightKg: 3.15,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA VEGETAL BARISTA ALMENDRA ORASI L",
    price: 3714,
    categoryPath: "Lácteos, Huevos > Lácteos vegetales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-VEGETAL-BARISTA-ALMENDRA-ORASI-L.jpg",
    ],
    brand: "ORASI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA VEGETAL BARISTA AVENA ORASI 500CC",
    price: 2519,
    categoryPath: "Lácteos, Huevos > Lácteos vegetales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-VEGETAL-BARISTA-AVENA-ORASI-500CC.jpg",
    ],
    brand: "ORASI",
    weightKg: 0.53,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA VEGETAL BARISTA AVENA ORASI L",
    price: 3611,
    categoryPath: "Lácteos, Huevos > Lácteos vegetales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-VEGETAL-BARISTA-AVENA-ORASI-L.jpg",
    ],
    brand: "ORASI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "BEBIDA VEGETAL BARISTA SOYA ORASI L",
    price: 3955,
    categoryPath: "Lácteos, Huevos > Lácteos vegetales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BEBIDA-VEGETAL-BARISTA-SOYA-ORASI-L.jpg",
    ],
    brand: "ORASI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "BETARRAGA 5 U",
    price: 2118,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/BETARRAGA-5-U.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "BOLSA BASURA 50X70 CM NEGRA VIRUTEX 10U",
    price: 919,
    categoryPath: "Limpieza > Accesorios de limpieza",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/BOLSA-BASURA-50X70-CM-NEGRA-VIRUTEX-10U.jpg",
    ],
    brand: "VIRUTEX",
    weightKg: 50,
    length: 40,
    width: 30,
    height: 12,
    unitLabel: "unidad",
  },
  {
    name: "BOLSA BASURA NEGRA VIRUTEX 70x90CM 10",
    price: 1609,
    categoryPath: "Limpieza > Accesorios de limpieza",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/BOLSA-BASURA-NEGRA-VIRUTEX-70x90CM-10.jpg",
    ],
    brand: "VIRUTEX",
    weightKg: 70,
    length: 40,
    width: 30,
    height: 12,
    unitLabel: "unidad",
  },
  {
    name: "BOLSA BASURA VITUTEX NEGRA 80x110CM 10U",
    price: 2225,
    categoryPath: "Limpieza > Accesorios de limpieza",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/BOLSA-BASURA-VITUTEX-NEGRA-80x110CM-10U.jpg",
    ],
    brand: "VIRUTEX",
    weightKg: 80,
    length: 40,
    width: 30,
    height: 12,
    unitLabel: "unidad",
  },
  {
    name: "BROCOLI U",
    price: 2620,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/brocol.avif",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI COLOMBIA CATURRA DECAF 1K",
    price: 47742,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-COLOMBIA-CATURRA-DECAF-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 1,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI COLOMBIA CATURRA DECAF 250G",
    price: 17881,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-COLOMBIA-CATURRA-DECAF-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 0.25,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI COLOMBIA TABI 1K",
    price: 34500,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-COLOMBIA-TABI-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 1,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI COLOMBIA TABI 250G",
    price: 12026,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-COLOMBIA-TABI-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 0.25,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI YELLOW BOURBON 1K",
    price: 34500,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-YELLOW-BOURBON-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 1,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE COLIBRI YELLOW BOURBON 250G",
    price: 12327,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-COLIBRI-YELLOW-BOURBON-1K.webp",
    ],
    brand: "COLIBRI",
    weightKg: 0.25,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CAFE JACOBS KRONUNG 200 G",
    price: 14834,
    categoryPath: "Despensa > Té y café",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CAFE-JACOB-KRONUNG-200-G.jpg",
    ],
    brand: "JACOB",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO CALUGAS CARNE MAGGI 12U",
    price: 1700,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-CALUGAS-CARNE-MAGGI-12U-1.webp",
    ],
    brand: "MAGGI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO CALUGAS COSTILLA MAGGI 12U",
    price: 1700,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-CALUGAS-COSTILLA-MAGGI-12U.webp",
    ],
    brand: "MAGGI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO CALUGAS GALLINA MAGGI 12U",
    price: 1700,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-CALUGAS-GALLINA-MAGGI-12U.webp",
    ],
    brand: "MAGGI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO CARNE CONCENTRADO POLVO TKF K",
    price: 3337,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-CARNE-CONCENTRADO-POLVO-TKF-K.jpg",
    ],
    brand: "TKF",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO CARNE MAGGI 850G",
    price: 4953,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-CARNE-MAGGI-850G.jpg",
    ],
    brand: "NESTLE",
    weightKg: 0.85,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO GALLINA MAGGI 850 G",
    price: 4967,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-GALLINA-MAGGI-850-G.jpg",
    ],
    brand: "MAGGI",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALDO POLLO CONCENTRADO POLVO TKF K",
    price: 3337,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALDO-POLLO-CONCENTRADO-POLVO-TKF-K.jpg",
    ],
    brand: "TKF",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CALLAMPAS SECAS K",
    price: 37127,
    categoryPath: "Frutas y Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CALLAMPAS-SECAS-K.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CANELA 15G",
    price: 648,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CANELA-15G.jpg",
    ],
    brand: "GOURMET",
    weightKg: 0.01,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CANELA ENTERA K",
    price: 31509,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CANELA-ENTERA.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CANELA POLVO K",
    price: 14636,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CANELA-15G-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CARNE DE SOJA 300G",
    price: 2759,
    categoryPath: "Productos veganos",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CARNE-DE-SOJA-300G.jpg",
    ],
    brand: "ABASTO",
    weightKg: 0.3,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CASTAÑA ALMIBAR TATITO FRASCO K",
    price: 7960,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CASTANA-ALMIBAR-TATITO-FRASCO-k-1.jpg",
    ],
    brand: "TATITO",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CASTAÑA CAJU K",
    price: 14969,
    categoryPath: "Frutas y Verduras > Frutos secos",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CASTANA-CAJU-K-1.jpg",
    ],
    brand: "OTRO",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEBOLLA EN POLVO K",
    price: 9669,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEBOLLA-EN-POLVO-K-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEBOLLA K",
    price: 2342,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEBOLLA-K-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEBOLLA MORADA K",
    price: 2899,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/02/Cebolla-Morada.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEPILLO DENTAL FLEXI COLGATE",
    price: 780,
    categoryPath: "Cuidado personal",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEPILLO-DENTAL-FLEXI-COLGATE.jpg",
    ],
    brand: "COLGATE",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEREAL CORNFLAKES K ECONOMICO",
    price: 6666,
    categoryPath: "Despensa > Cereales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEREAL-CORNFLAKES-K-ECONOMICO.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEREZA CONFITADA 500G",
    price: 3787,
    categoryPath: "Despensa > Harinas y repostería",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/ChatGPT-Image-19-feb-2026-10_51_41-a.m.-2.jpg",
    ],
    brand: "ROCOFRUT",
    weightKg: 0.5,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEREZA JUGO SIN CAROZO PERELLO GALON 3K",
    price: 13580,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEREZA-JUGO-SIN-CAROZO-PERELLO-GALON-3K-1.jpg",
    ],
    brand: "PERELLO",
    weightKg: 3,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CEREZA JUGO SIN CAROZO PERELLO LATA 580G",
    price: 3337,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CEREZA-JUGO-SIN-CAROZO-PERELLO-LATA-580G-1.jpg",
    ],
    brand: "PERELLO",
    weightKg: 0.58,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CERVEZA SIX PACK CRISTAL 470CC",
    price: 7643,
    categoryPath: "Licores, Bebidas y Aguas > Cervezas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CERVEZA-SIX-PACK-CRISTAL-470CC.webp",
    ],
    brand: "CRISTAL",
    weightKg: 0.49,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CHAMPIÑON ENTERO DEYCO 400G",
    price: 2149,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHAMPINON-ENTERO-DEYCO-400G.jpg",
    ],
    brand: "DEYCO",
    weightKg: 0.4,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHAMPIÑON LAMINADO DEYCO 400G",
    price: 2143,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHAMPINON-LAMINADO-DEYCO-400G.jpg",
    ],
    brand: "DEYCO",
    weightKg: 0.4,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHAMPIÑON LAMINADO DEYCO GALON",
    price: 6793,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHAMPINON-LAMINADO-DEYCO-GALON.jpg",
    ],
    brand: "DEYCO",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHANCACA DELICIOSA 400G",
    price: 1898,
    categoryPath: "Despensa > Azúcar y endulzantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHANCACA-DELICIOSA-400G.jpg",
    ],
    brand: "DELICIOSA",
    weightKg: 0.4,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHIA K",
    price: 7457,
    categoryPath: "Despensa > Cereales",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHIA-K-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHOCLITOS COCKTAIL ENTERO DEYCO 425G",
    price: 2276,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHOCLITOS-COCKTAIL-ENTERO-DEYCO-425G-1-e1771423628965.webp",
    ],
    brand: "DEYCO",
    weightKg: 0.42,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHOCLITOS COCKTAIL TROZO DEYCO 425G",
    price: 2218,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHOCLITOS-COCKTAIL-TROZO-DEYCO-425G-e1771423800957.webp",
    ],
    brand: "DEYCO",
    weightKg: 0.42,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHOCLO PERUANO K",
    price: 8067,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHOCLO-PERUANO-K-1.jpg",
    ],
    brand: "OTRO",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHORITOS ACEITE DEYCO 190G",
    price: 1561,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHORITOS-ACEITE-DEYCO-190G.webp",
    ],
    brand: "DEYCO",
    weightKg: 0.19,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHORITOS ACEITE SAN JOSE 190G",
    price: 1264,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHORITOS-ACEITE-SAN-JOSE-190G.webp",
    ],
    brand: "SAN JOSE",
    weightKg: 0.19,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHORITOS NATURAL SAN JOSE 190G",
    price: 1689,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHORITOS-NATURAL-SAN-JOSE-190G.webp",
    ],
    brand: "SAN JOSE",
    weightKg: 0.19,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHUCRUT DON JUAN K",
    price: 3713,
    categoryPath: "Despensa > Acetos, sucedáneos y vinagres",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHUCRUT-DON-JUAN-K.jpg",
    ],
    brand: "DON JUAN",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CHUÑO K",
    price: 2899,
    categoryPath: "Despensa > Harinas y repostería",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CHUNO-K-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CIF CREMA 750CC",
    price: 2781,
    categoryPath: "Limpieza > Limpieza de baños",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/CIF-CREMA-750CC.jpg",
    ],
    brand: "CIF",
    weightKg: 0.79,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CILANTRO K",
    price: 3123,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/02/cilan.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CIRUELAS SIN CAROZO K",
    price: 7715,
    categoryPath: "Frutas y Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CIRUELAS-SIN-CAROZO-K-1.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLARA HUEVO POLVO 500G DELISSA",
    price: 20308,
    categoryPath: "Lácteos, Huevos > Huevos",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/CLARA-HUEVO-POLVO-500G-DELISSA.jpg",
    ],
    brand: "DELISSA",
    weightKg: 0.5,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLARA HUEVO POLVO ESTANDAR 500G COCTELES DELISSA",
    price: 13417,
    categoryPath: "Lácteos, Huevos > Huevos",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/CLARA-HUEVO-POLVO-ESTANDAR-500G-COCTELES-DELISSA.jpg",
    ],
    brand: "DELISSA",
    weightKg: 0.5,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLAVO DE OLOR ENTERO K",
    price: 32654,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLAVO-DE-OLOR-ENTERO-K.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLAVO DE OLOR MOLIDO K",
    price: 22500,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLAVO-DE-OLOR-MOLIDO-K.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLORO CLORINDA L",
    price: 1615,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLORO-CLORINDA-L.webp",
    ],
    brand: "CLORINDA",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CLORO GEL CLORINDA 900CC",
    price: 2674,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/Cloro-gel-Clorinda-original-900-ml.webp",
    ],
    brand: "CLORINDA",
    weightKg: 0.95,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CLORO GEL LAVANDA IGENIX 900 CC",
    price: 1615,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLORO-GOLDEN-5L.webp",
    ],
    brand: "",
    weightKg: 0.95,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CLORO GEL TRADICIONAL IGENIX 900 CC",
    price: 1615,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLORO-GEL-TRADICIONAL-IGENIX-900-CC.jpg",
    ],
    brand: "",
    weightKg: 0.95,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CLORO GOLDEN 5L",
    price: 2517,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2025/12/CLORO-GOLDEN-5L.jpg",
    ],
    brand: "GOLDEN",
    weightKg: 5.25,
    length: 20,
    width: 15,
    height: 35,
    unitLabel: "unidad",
  },
  {
    name: "CLORO LIQUIDO TRADIDIONAL IGENIX 1 LT",
    price: 1176,
    categoryPath: "Limpieza > Desinfectantes",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CLORO-LIQUIDO-1KG-IGENIX.webp",
    ],
    brand: "",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COCKTAIL FRUTAS ACONCAGUA 820G",
    price: 2391,
    categoryPath: "Despensa > Conservas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/COCKTAIL-FRUTAS-ACONCAGUA-820G.avif",
    ],
    brand: "ACONCAGUA",
    weightKg: 0.82,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COCO EN ESCAMAS K",
    price: 12186,
    categoryPath: "Despensa > Harinas y repostería",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/COCO-EN-ESCAMAS-K.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COCO RALLADO FINO BLANCO K",
    price: 10357,
    categoryPath: "Despensa > Harinas y repostería",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/COCO-RALLADO-FINO-BLANCO-K.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COFIAS NANOLIFE 100U",
    price: 3177,
    categoryPath: "Despensa > Harinas y repostería",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/COFIAS-NANOLIFE-100U.jpg",
    ],
    brand: "NANOLIFE",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COLIFLOR U",
    price: 2620,
    categoryPath: "Frutas y Verduras > Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/02/coliflor.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COMINO K",
    price: 5081,
    categoryPath: "Despensa > Condimentos y especias",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/COMINO-K.webp",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "COÑAC TRES PALOS 750CC",
    price: 4976,
    categoryPath: "Licores, Bebidas y Aguas > Destilados",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CONAC-TRES-PALOS-1LT-X-UNIDAD-ARRIBA-DE-TRES-UNIDADES.webp",
    ],
    brand: "TRES PALOS",
    weightKg: 0.79,
    length: 6,
    width: 6,
    height: 20,
    unitLabel: "unidad",
  },
  {
    name: "CRAMBERRY DESHIDRATADO K",
    price: 8966,
    categoryPath: "Frutas y Verduras",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CRAMBERRY-DESHIDRATADO.jpg",
    ],
    brand: "GRANEL",
    weightKg: 1,
    length: 20,
    width: 15,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA ACIDA QUILLAYES 200G",
    price: 2218,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-ACIDA-QUILLAYES-200G.webp",
    ],
    brand: "QUILLAYES",
    weightKg: 0.2,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA AVELLANA CARAT NUXEL 5K",
    price: 85041,
    categoryPath: "Despensa",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-AVELLANA-CARAT-NUXEL-5K-1.jpg",
    ],
    brand: "CARAT",
    weightKg: 5,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA AVELLANA NUTELLA 350G",
    price: 7232,
    categoryPath: "Despensa ",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-AVELLANA-NUTELLA-350G.webp",
    ],
    brand: "NUTELLA",
    weightKg: 0.35,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA AVELLANA NUTELLA 3K",
    price: 47482,
    categoryPath: "Despensa",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-AVELLANA-NUTELLA-3K.webp",
    ],
    brand: "NUTELLA",
    weightKg: 3,
    length: 25,
    width: 20,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA CHANTILLY CHOCOLATE GOURMET 430G",
    price: 4967,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-CHANTILLY-CHOCOLATE-GOURMET-430G.png",
    ],
    brand: "GOURMET",
    weightKg: 0.43,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA CHANTILLY GOURMET 420G",
    price: 4070,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-CHANTILLY-GOURMET-420G.webp",
    ],
    brand: "GOURMET",
    weightKg: 0.42,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA CHANTILLY LUCUMA GOURMET 370G",
    price: 4397,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-CHANTILLY-LUCUMA-GOURMET-370G.webp",
    ],
    brand: "GOURMET",
    weightKg: 0.37,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA CHANTILLY POLVO PURATOS 450G",
    price: 4254,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/Crema-Chantilly.webp",
    ],
    brand: "PURATOS",
    weightKg: 0.45,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
  {
    name: "CREMA CHANTILLY PREMIUM PURATOS 400G",
    price: 4172,
    categoryPath: "Lácteos, Huevos > Cremas",
    images: [
      "https://cibox.cl/wp-content/uploads/2026/01/CREMA-CHANTILLY-PREMIUM-PURATOS-400G.webp",
    ],
    brand: "PURATOS",
    weightKg: 0.4,
    length: 10,
    width: 10,
    height: 10,
    unitLabel: "unidad",
  },
];

const buildDescription = (name, brand, categoryName) => {
  return `${name}${brand ? ` de marca ${brand}` : ""}${
    categoryName ? ` en categoría ${categoryName}` : ""
  }.`;
};

const findApprovedVendor = async () => {
  const vendor = await Vendor.findOne({
    approved: true,
    is_active: true,
  });

  if (!vendor) {
    throw new Error(
      "No existe un vendor aprobado y activo para asignar a los productos",
    );
  }

  return {
    id: vendor._id.toString(),
    name: vendor.store_name,
  };
};

const resolveCategoryByPath = async (categoryPath) => {
  if (!categoryPath) {
    throw new Error("Falta categoryPath en un producto");
  }

  const parts = categoryPath
    .split(">")
    .map((item) => item.trim())
    .filter(Boolean);

  let parent = null;
  let found = null;

  for (const part of parts) {
    found = await Category.findOne({
      name: part,
      parent_id: parent ? parent._id : null,
      is_active: true,
    });

    if (!found) {
      throw new Error(
        `No se encontró la categoría/subcategoría: ${categoryPath}`,
      );
    }

    parent = found;
  }

  return found;
};

const upsertProduct = async (rawProduct, vendorData) => {
  const category = await resolveCategoryByPath(rawProduct.categoryPath);

  const images = Array.isArray(rawProduct.images) ? rawProduct.images : [];
  const thumbnail = images[0] || "";

  const payload = {
    vendor: vendorData,
    product_type: "simple",
    name: rawProduct.name,
    images,
    thumbnail,
    search_name: normalizeText(rawProduct.name),
    description: buildDescription(
      rawProduct.name,
      rawProduct.brand,
      category.name,
    ),
    category: {
      id: category._id.toString(),
      name: category.name,
    },
    pricing: {
      tiers: [
        {
          min_qty: 1,
          price: Number(rawProduct.price),
          label: rawProduct.unitLabel || "unidad",
        },
      ],
    },
    box_items: [],
    stock: 25,
    is_active: true,
    cibox_plus: {
      enabled: false,
    },
    sku: rawProduct.sku || "",
    brand: rawProduct.brand || "",
    weight: {
      value: Math.round(Number(rawProduct.weightKg || 0) * 1000),
      unit: "g",
    },
    dimensions: {
      length: Number(rawProduct.length || 0),
      width: Number(rawProduct.width || 0),
      height: Number(rawProduct.height || 0),
      unit: "cm",
    },
  };

  const product = await Product.findOneAndUpdate(
    {
      name: rawProduct.name,
      "vendor.id": vendorData.id,
    },
    payload,
    {
      new: true,
      upsert: true,
      setDefaultsOnInsert: true,
      runValidators: true,
    },
  );

  return product;
};

export const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Mongo conectado");

    const vendorData = await findApprovedVendor();
    console.log("Vendor usado:", vendorData);

    for (const item of products) {
      const product = await upsertProduct(item, vendorData);
      console.log(`OK: ${product.name}`);
    }

    console.log("Seed de productos completado");
    process.exit(0);
  } catch (error) {
    console.error("ERROR SEED PRODUCTS:", error);
    process.exit(1);
  }
};
